list: $/itmaker/dtpapp/models/call/columns.yaml
modelClass: Itmaker\DtpApp\Models\Call
title: Calls
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'itmaker/dtpapp/calls/update/:id'
