list: $/itmaker/dtpapp/models/slide/columns.yaml
modelClass: Itmaker\DtpApp\Models\Slide
title: Slides
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'itmaker/dtpapp/slides/update/:id'
