list: $/itmaker/dtpapp/models/rate/columns.yaml
modelClass: Itmaker\DtpApp\Models\Rate
title: Rates
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'itmaker/dtpapp/rates/update/:id'
