name: Rates
form: $/itmaker/dtpapp/models/rate/fields.yaml
modelClass: Itmaker\DtpApp\Models\Rate
defaultRedirect: itmaker/dtpapp/rates
create:
    redirect: 'itmaker/dtpapp/rates/update/:id'
    redirectClose: itmaker/dtpapp/rates
update:
    redirect: itmaker/dtpapp/rates
    redirectClose: itmaker/dtpapp/rates
