list: $/itmaker/dtpapp/models/tarif/columns.yaml
modelClass: Itmaker\DtpApp\Models\Tarif
title: Tarifs
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'itmaker/dtpapp/tarifs/update/:id'
