name: EmployeesLocations
form: $/itmaker/dtpapp/models/employeeslocation/fields.yaml
modelClass: Itmaker\DtpApp\Models\EmployeesLocation
defaultRedirect: itmaker/dtpapp/employeeslocations
create:
    redirect: 'itmaker/dtpapp/employeeslocations/update/:id'
    redirectClose: itmaker/dtpapp/employeeslocations
update:
    redirect: itmaker/dtpapp/employeeslocations
    redirectClose: itmaker/dtpapp/employeeslocations
